### ISSUE TITLE
OVA v1 or v2? 

### ISSUE THREAD

**Issue by ewjannece** [lamw/vsphere-8-lab-deployment#1]
Thank you for this script and being such a supporter of homelabs!
I see in the instructions / README.MD that we're suppose to use "Nested_ESXi8.0_IA_Appliance_Template_v1.ova"

But in the script it references Nested_ESXi8.0_IA_Appliance_Template_v2.ova and there is indeed a download of v2.

 `# Full Path to the Nested ESXi 8.0 VA & Extracted VCSA 8.0 ISO
$NestedESXiApplianceOVA = "/Volumes/Storage/Software/VMware/Lab/Nested_ESXi8.0_IA_Appliance_Template_v2.ova"
$VCSAInstallerPath = "/Volumes/Storage/Software/VMware/Lab/VMware-VCSA-all-8.0.0-20519528"`

Which one should we be using?

**Comment by lamw** [comment]
v2, README has been fixed
