### ISSUE TITLE
272 and 273 are the same?

### ISSUE THREAD

**Issue by B-Art** [lamw/vsphere-8-lab-deployment#10]
My-Logger "Adding vmnic2/vmnic3 for `"$VMNetwork`" to passthrough to Nested ESXi VMs ..."
        New-NetworkAdapter -VM $vm -Type Vmxnet3 -NetworkName $VMNetwork -StartConnected -confirm:$false | Out-File -Append -LiteralPath $verboseLogFile
        New-NetworkAdapter -VM $vm -Type Vmxnet3 -NetworkName $VMNetwork -StartConnected -confirm:$false | Out-File -Append -LiteralPath $verboseLogFile

**Comment by lamw** [comment]
Yes, this is by design as I'm adding an additional two NIC and repeating the operation is one way to achieve this outcome :)
