### ISSUE TITLE
Add Section to Requirements about Port Group setting for Promiscuous Mode, etc...

### ISSUE THREAD

**Issue by andrewjmoser** [lamw/vsphere-8-lab-deployment#6]
I didn't see it anywhere in the requirements, and it had been a while since I deployed a nested environment, but I forgot to enable promiscuous mode settings on the port group I created for this, and I kept bombing out without being able to contact the ESX hosts.   Once I figured that out, everything worked fine, but maybe add that as a requirement in the requirements section?   If its already there someplace else that I missed, my apologies, I didn't see it when I went to look.

**Comment by lamw** [comment]
Done
