### ISSUE TITLE
ARM aarch64 architecture based powershell/host not supported for VSCA deployment

### ISSUE THREAD

**Issue by waxling** [lamw/vsphere-8-lab-deployment#7]
This is a bit obvious once you look at the reason - due to the VSCA portion of the script using the binary installer on the ISO, only x86, x32 and mac is supported. Could be worth pointing this out in the instructions - or check in the script.

to reproduce:
1. install an ARM ubuntu 22.04 host to run the script
```
PS /home/bot01> uname -a
Linux pi-bot 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
````
3. follow the powershell install instructions for ARM on ubuntu:
```
PS /home/bot01> Get-PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      3
```
4. run the installer - all steps work until the vsca install phase:
```
/home/bot01/images/installer/vcsa-cli-installer/lin64/vcsa-deploy: line 15: /home/bot01/images/installer/vcsa-cli-installer/lin64/vcsa-deploy.bin: cannot execute binary file: Exec format error
```

**Comment by lamw** [comment]
VCSA Installer is indeed an x86 application, so it won't run on arm64 system ... If you're using Apple M1/M2 and Rosetta is installed, it would emulate x86 and run. However, for standard arm64 system, this is expected.
